## ╭──────────────────────────────────────────────╮
## │                   Layout                     │
## ╰──────────────────────────────────────────────╯

Layout/LineLength:
  Enabled: false

## ╭──────────────────────────────────────────────╮
## │                  Metrics                     │
## ╰──────────────────────────────────────────────╯

Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false

## ╭──────────────────────────────────────────────╮
## │                   Style                      │
## ╰──────────────────────────────────────────────╯

Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
