## ╭──────────────────────────────────────────────╮
## │                    Taps                      │
## ╰──────────────────────────────────────────────╯

tap "nikitabobko/tap"

## ╭──────────────────────────────────────────────╮
## │                  Formulae                    │
## ╰──────────────────────────────────────────────╯

# Language Servers
brew "jdtls"
brew "pyright"
brew "lua-language-server"
brew "marksman"
brew "mypy"
brew "ruff"
brew "stylua"
brew "yaml-language-server"
brew "bash-language-server"

brew "xz"
brew "openssl@3"
brew "libyaml"
brew "aws-sam-cli"
brew "cairo"
brew "fd"
brew "fzf"
brew "google-java-format"
brew "python@3.12"
brew "librsvg"
brew "graphviz"
brew "jq"
brew "libffi"
brew "mise"
brew "neovim"
brew "ruby"
brew "shfmt"
brew "tcl-tk"
brew "tmux"
brew "tree"
brew "unison"
brew "xsel"
brew "zlib"
brew "oh-my-posh"

## ╭──────────────────────────────────────────────╮
## │                   Casks                      │
## ╰──────────────────────────────────────────────╯

cask "aerospace"
cask "alacritty"
cask "karabiner-elements"
cask "font-jetbrains-mono-nerd-font"
