require("lazy").setup({
    require("plugins.plenary"),
    require("plugins.base46"),
    require("plugins.ui"),
    require("plugins.volt"),
    require("plugins.menu"),
    require("plugins.minty"),
    require("plugins.nvim-web-devicons"),
    require("plugins.indent-blankline"),
    require("plugins.nvim-tree"),
    require("plugins.conform"),
    require("plugins.which-key"),
    require("plugins.gitsigns"),
    require("plugins.nvim-cmp"),
    require("plugins.telescope"),
    require("plugins.treesitter"),
    require("plugins.nvim-lint"),
    require("plugins.vim-tmux-navigator"),
    require("plugins.oil"),
}, {
    defaults = { lazy = true },
    install = { colorscheme = { "nvchad" } },
    ui = {
        icons = {
            ft = "",
            lazy = "󰂠 ",
            loaded = "",
            not_loaded = "",
        },
    },
    performance = {
        rtp = {
            disabled_plugins = {
                "2html_plugin",
                "tohtml",
                "getscript",
                "getscriptPlugin",
                "gzip",
                "logipat",
                "netrw",
                "netrwPlugin",
                "netrwSettings",
                "netrwFileHandlers",
                "matchit",
                "tar",
                "tarPlugin",
                "rrhelper",
                "spellfile_plugin",
                "vimball",
                "vimballPlugin",
                "zip",
                "zipPlugin",
                "tutor",
                "rplugin",
                "syntax",
                "synmenu",
                "optwin",
                "compiler",
                "bugreport",
                "ftplugin",
            },
        },
    },
})
